# Generated by Django 3.2.25 on 2025-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='Food_category',
            new_name='Food_Category',
        ),
        migrations.AlterField(
            model_name='admin',
            name='Food_Image',
            field=models.ImageField(upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Food_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
