# Generated by Django 3.2.25 on 2025-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_admin_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Food_Image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
