# Generated by Django 3.2.25 on 2025-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_admin_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Food_Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
