# Generated by Django 3.2.25 on 2025-02-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
